//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOUusarioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/AplicacionSencilla.Entidades.WCF.Usuarios" +
        "")]
    [System.SerializableAttribute()]
    public partial class DTOUusarioRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo[] CuerpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo[] Cuerpo {
            get {
                return this.CuerpoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoField, value) != true)) {
                    this.CuerpoField = value;
                    this.RaisePropertyChanged("Cuerpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOResultado", Namespace="http://schemas.datacontract.org/2004/07/AplicacionSencilla.Entidades.WCF")]
    [System.SerializableAttribute()]
    public partial class DTOResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.EnumsCodigoRespuesta CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDePilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.EnumsCodigoRespuesta Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDePila {
            get {
                return this.ErrorDePilaField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDePilaField, value) != true)) {
                    this.ErrorDePilaField = value;
                    this.RaisePropertyChanged("ErrorDePila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOUsuarioCuerpo", Namespace="http://schemas.datacontract.org/2004/07/AplicacionSencilla.Entidades.WCF.Usuarios" +
        "")]
    [System.SerializableAttribute()]
    public partial class DTOUsuarioCuerpo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOLoginCuerpo LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOLoginCuerpo Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroIdentificacion {
            get {
                return this.NumeroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIdentificacionField, value) != true)) {
                    this.NumeroIdentificacionField = value;
                    this.RaisePropertyChanged("NumeroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoIdentificacion {
            get {
                return this.TipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIdentificacionField, value) != true)) {
                    this.TipoIdentificacionField = value;
                    this.RaisePropertyChanged("TipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOLoginCuerpo", Namespace="http://schemas.datacontract.org/2004/07/AplicacionSencilla.Entidades.WCF.Usuarios" +
        "")]
    [System.SerializableAttribute()]
    public partial class DTOLoginCuerpo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.CodigoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/AplicacionSencilla.Entidades")]
    public enum EnumsCodigoRespuesta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unauthorized = 401,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 404,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStatus = 406,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestTimeout = 408,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalServiceError = 500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotImplemented = 501,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOUsuarioSolicitud", Namespace="http://schemas.datacontract.org/2004/07/AplicacionSencilla.Entidades.WCF.Usuarios" +
        "")]
    [System.SerializableAttribute()]
    public partial class DTOUsuarioSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AplicacionSencillaServicio.IAplicacionSencillaServicio")]
    public interface IAplicacionSencillaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/ObtenerUusuarios", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/ObtenerUusuariosResponse")]
        AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUusarioRespuesta ObtenerUusuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/ObtenerUusuarios", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/ObtenerUusuariosResponse")]
        System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUusarioRespuesta> ObtenerUusuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/BorrarUusuarios", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/BorrarUusuariosResponse")]
        AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado BorrarUusuarios(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioSolicitud usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/BorrarUusuarios", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/BorrarUusuariosResponse")]
        System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado> BorrarUusuariosAsync(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioSolicitud usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/AgregarUusuarios", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/AgregarUusuariosResponse")]
        AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado AgregarUusuarios(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/AgregarUusuarios", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/AgregarUusuariosResponse")]
        System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado> AgregarUusuariosAsync(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/Login", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/LoginResponse")]
        AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado Login(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAplicacionSencillaServicio/Login", ReplyAction="http://tempuri.org/IAplicacionSencillaServicio/LoginResponse")]
        System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado> LoginAsync(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAplicacionSencillaServicioChannel : AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.IAplicacionSencillaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AplicacionSencillaServicioClient : System.ServiceModel.ClientBase<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.IAplicacionSencillaServicio>, AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.IAplicacionSencillaServicio {
        
        public AplicacionSencillaServicioClient() {
        }
        
        public AplicacionSencillaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AplicacionSencillaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AplicacionSencillaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AplicacionSencillaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUusarioRespuesta ObtenerUusuarios() {
            return base.Channel.ObtenerUusuarios();
        }
        
        public System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUusarioRespuesta> ObtenerUusuariosAsync() {
            return base.Channel.ObtenerUusuariosAsync();
        }
        
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado BorrarUusuarios(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioSolicitud usuario) {
            return base.Channel.BorrarUusuarios(usuario);
        }
        
        public System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado> BorrarUusuariosAsync(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioSolicitud usuario) {
            return base.Channel.BorrarUusuariosAsync(usuario);
        }
        
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado AgregarUusuarios(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario) {
            return base.Channel.AgregarUusuarios(usuario);
        }
        
        public System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado> AgregarUusuariosAsync(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario) {
            return base.Channel.AgregarUusuariosAsync(usuario);
        }
        
        public AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado Login(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario) {
            return base.Channel.Login(usuario);
        }
        
        public System.Threading.Tasks.Task<AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOResultado> LoginAsync(AplñicacionSencilla.FrontEnd.AplicacionSencillaServicio.DTOUsuarioCuerpo usuario) {
            return base.Channel.LoginAsync(usuario);
        }
    }
}
